### PR TITLE
Added resources to the resources page.

### PR DESCRIPTION
**Pull request by jarroldp**
Also added unordered list classes (multicolumn-left and multicolumn-other) to vertically align the descriptions of the list items of a list.

```
modified:   _posts/2015-04-23-resources.md
modified:   assets/css/main.css
```

I have presumed to commit only the files I modified, not the files that were modified by serving jekyll. If correct, it may be useful to make the presumption explicit in CONTRIBUTING.md. The additional files modified by serving jekyll are,

```
deleted:  site/:slug.html
modified: site/CONTRIBUTING.md
modified: site/assets/css/main.css
modified: site/feed.xml

Untracked files:
    site/code-of-ethics.html
    site/daniel.html
    site/eli.html
    site/emily.html
    site/ian.html
    site/lucy.html
    site/resources.html
    site/thursday-meeting.html
```

merge_request_20150519_1
merge_request_20150519_2

### CODE REVIEW

**Comment by nobane** [comment]
:+1:

**Comment by lucywyman** [comment]
@jarroldp The only thing is if you can get rid of the indent on the raw html (so it's right up against the side of the text editor), and move all the bullet points below it to be that way as well.  When I built it it read the html as content and not html, but doing that should fix it! Thanks!

**Comment by jarroldp** [comment]
I originally attempted to use multiple asterisks rather than indentation and single asterisks, but that caused the asterisks to be parsed as content rather than as lists when I served the website in jekyll.

merge_request_20150520_noindent_multiasterisk

As soon as I remove the indentation of the div tag, the flow of the resources list becomes broken, regardless of whether the ul, li, and comment tags are indented.

merge_request_20150519_htmlnoindent

I doubt it is causing your build to parse the html as content, but I pushed an intermediate commit that replaced the last remaining tabs with 4 spaces. A third commit, with the html unindented, looks like this:

merge_request_20150522_3

If you test the three commits of my branch and none of them build with the appearance of my original screen captures, I can replace the html with markdown, though the descriptions won't vertically align perfectly, even if I use non-breaking spaces.

merge_request_20150521_nohtml

**Comment by jarroldp** [comment]
The changes didn't fix the problem, which appears to be that your build is removing the newline between the div tag and the last prior markdown line and the newline between the div end tag and the first subsequent markdown line. Perhaps adding a blank line between the markdown and the html would fix the problem. Can the merge be reverted? I see a revert button at the end of the merge message.

**Pull request merged**
